# Generated by Django 2.2.5 on 2019-11-08 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_remove_leavingmessage_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavingmessage',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_msgs', to='operation.LeavingMessage', verbose_name='上级留言'),
        ),
    ]
