# Generated by Django 2.2.5 on 2019-09-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20190925_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body_html',
            field=models.TextField(verbose_name='HTML格式正文'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body_md',
            field=models.TextField(verbose_name='Markdown格式正文'),
        ),
    ]
