# Generated by Django 2.2.5 on 2019-09-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20190925_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body_html',
        ),
        migrations.RemoveField(
            model_name='article',
            name='body_md',
        ),
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(default='', verbose_name='正文'),
        ),
    ]
